if (FALSE) {
  # M = 6 -----------------------------------------------------------------------------------------------------------
  {
    p1 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_6_n_train_1000_n_test_1000_rho_0.01_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.01") + guides(color = FALSE)

    p2 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_6_n_train_1000_n_test_1000_rho_0.11_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.11") + guides(color = FALSE)

    p3 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_6_n_train_1000_n_test_1000_rho_0.31_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_dt_MAE.rds",
                      index_combinations = NULL,
                      # only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.31") + guides(color = FALSE)

    p4 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_6_n_train_1000_n_test_1000_rho_0.41_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.41") + guides(color = FALSE)

    p5 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_6_n_train_1000_n_test_1000_rho_0.61_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.61") + guides(color = FALSE)

    p6 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_6_n_train_1000_n_test_1000_rho_0.71_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.71") + guides(color = FALSE)

    p7 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_6_n_train_1000_n_test_1000_rho_0.81_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.81") + guides(color = FALSE)

    p8 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_6_n_train_1000_n_test_1000_rho_0.91_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      #only_these_sampling_methods = c("unique", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_equal_weights", "unique_SW", "unique_paired_SW", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.91")

    gridExtra::grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, nrow = 2)

  }







  # M = 10 ----------------------------------------------------------------------------------------------------------
  {
    p1 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_10_n_train_1000_n_test_1000_rho_0.04_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.04") + guides(color = FALSE)

    p2 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_10_n_train_1000_n_test_1000_rho_0.14_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.14") + guides(color = FALSE)

    p3 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_10_n_train_1000_n_test_1000_rho_0.24_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.24") + guides(color = FALSE)

    p4 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_10_n_train_1000_n_test_1000_rho_0.34_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.34") + guides(color = FALSE)

    p5 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_10_n_train_1000_n_test_1000_rho_0.64_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.64") + guides(color = FALSE)

    p6 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_10_n_train_1000_n_test_1000_rho_0.74_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.74") + guides(color = FALSE)

    p7 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_10_n_train_1000_n_test_1000_rho_0.84_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.84") + guides(color = FALSE)

    p8 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_10_n_train_1000_n_test_1000_rho_0.94_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.94")



    gridExtra::grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, nrow = 2)
  }


  ## With extra samples of coalitions --------------------------------------------------------------------------------


  {
    only_these_sampling_methods = c("unique", "unique_unif", "unique_SW", "unique_equal_weights",
                                    "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif",
                                    "unique_paired_SW", "unique_paired_equal_weights", "unique_paired_equal_weights_1000",
                                    "unique_paired_equal_weights_5000", "unique_paired_equal_weights_10000",
                                    "unique_paired_equal_weights_50000", "unique_paired_equal_weights_100000",
                                    "unique_paired_equal_weights_symmetric", "paired_coalitions",
                                    "single_mean_coalition_effect")

    only_these_sampling_methods = c("unique_paired_SW",
                                    "unique_paired_equal_weights",
                                    "unique_paired_equal_weights_1000",
                                    "unique_paired_equal_weights_5000",
                                    "unique_paired_equal_weights_10000",
                                    "unique_paired_equal_weights_50000",
                                    "unique_paired_equal_weights_100000",
                                    "paired_coalitions")
    rhos = c(0,0.05,0.1,0.2,0.5,0.7,0.9,0.9)
    rho_equi = FALSE
    figs = list()
    for (rho_idx in seq_along(rhos)) {
      rho = rhos[rho_idx]
      figs[[rho_idx]] = plot_results(file_path = paste0("/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_10_n_train_1000_n_test_1000_rho_", rho, "_equi_", rho_equi ,"_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_dt_MAE.rds"),
                                     index_combinations = NULL,
                                     only_these_sampling_methods = only_these_sampling_methods,
                                     figures_to_make = c("figure_CI",
                                                         "figure_mean",
                                                         "figure_median",
                                                         "figure_lines",
                                                         "figure_boxplot",
                                                         "figure_lines_boxplot",
                                                         "figure_boxplot_lines"),
                                     ggplot_theme = NULL,
                                     brewer_palette = NULL,
                                     brewer_direction = 1,
                                     flip_coordinates = FALSE,
                                     legend_position = NULL,
                                     scale_y_log10 = TRUE,
                                     scale_x_log10 = FALSE,
                                     n.dodge = 2,
                                     plot_figures = FALSE)$figure_mean + ggplot2::ggtitle(paste0("rho = ", rho, " (equi = ", rho_equi, ")"))
      if (rho_idx != length(rhos)) {
        figs[[rho_idx]] = figs[[rho_idx]] + ggplot2::guides(color = "none")
      }

    }
    gridExtra::grid.arrange(grobs = figs, nrow = 2)
  }



  # M = 12 ----------------------------------------------------------------------------------------------------------
  {
    p1 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_12_n_train_1000_n_test_1000_rho_0.01_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_3_-1_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.01") + guides(color = FALSE)

    p2 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_12_n_train_1000_n_test_1000_rho_0.11_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_3_-1_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.11") + guides(color = FALSE)

    p3 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_12_n_train_1000_n_test_1000_rho_0.31_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_3_-1_dt_MAE.rds",
                      index_combinations = NULL,
                      # only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.31") + guides(color = FALSE)

    p4 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_12_n_train_1000_n_test_1000_rho_0.41_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_3_-1_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.41") + guides(color = FALSE)

    p5 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_12_n_train_1000_n_test_1000_rho_0.61_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_3_-1_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.61") + guides(color = FALSE)

    p6 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_12_n_train_1000_n_test_1000_rho_0.71_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_3_-1_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.71") + guides(color = FALSE)

    p7 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_12_n_train_1000_n_test_1000_rho_0.81_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_3_-1_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.81") + guides(color = FALSE)

    p8 = plot_results(file_path = "/Users/larsolsen/PhD/Paper3/Paper3_save_location/M_12_n_train_1000_n_test_1000_rho_0.91_equi_TRUE_betas_2_10_0.25_-3_-1_1.5_-0.5_10_1.25_1.5_-2_3_-1_dt_MAE.rds",
                      index_combinations = NULL,
                      #only_these_sampling_methods = c("unique", "unique_equal_weights", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_unif", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      only_these_sampling_methods = c("unique", "unique_SW", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_SW", "unique_paired_equal_weights", "paired_coalitions"),
                      #only_these_sampling_methods = c("unique", "unique_equal_weights_symmetric", "unique_paired", "unique_paired_equal_weights", "unique_SW", "unique_paired_SW", "paired_coalitions"),
                      figures_to_make = c("figure_CI",
                                          "figure_mean",
                                          "figure_median",
                                          "figure_lines",
                                          "figure_boxplot",
                                          "figure_lines_boxplot",
                                          "figure_boxplot_lines"),
                      ggplot_theme = NULL,
                      brewer_palette = NULL,
                      brewer_direction = 1,
                      flip_coordinates = FALSE,
                      legend_position = NULL,
                      scale_y_log10 = TRUE,
                      scale_x_log10 = FALSE,
                      n.dodge = 2,
                      plot_figures = FALSE)$figure_mean + ggplot2::ggtitle("rho = 0.91")

    gridExtra::grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, nrow = 2)

  }
}
